{% set name = "hepconvert" %}
{% set version = "1.4.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hepconvert-{{ version }}.tar.gz
  sha256: d2eac16909e03f67f528348b840fe4f4c5f8cfba3cc5707b284e19c2e6f56868

build:
  entry_points:
    - hepconvert = hepconvert.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - uproot >=5.0.0
    - click >=8.1
    - click-default-group >=1.2

test:
  imports:
    - hepconvert
  commands:
    - pip check
    - hepconvert --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/scikit-hep/hepconvert
  summary: File conversion package.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://hepconvert.readthedocs.io/
  dev_url: https://github.com/scikit-hep/hepconvert

extra:
  recipe-maintainers:
    - matthewfeickert
    - zbilodea
    - jpivarski
    - conda-forge/scikit-hep
